name: Snippet Generator

on:
  #schedule:
  #  - cron: '0 0 * * 1'

  workflow_dispatch:

jobs:
  generate:
    name: Regenerate PewPew Snippets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run the generator
        shell: pwsh
        run: | 
          Set-Location ${{ github.workspace }}
          ./generator/generate_snippets.ps1

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit --all -m "Regenerated snippets"
          git push
